name: lando
env_file:
  - lando.env
excludes:
  - node_modules
proxy:
  metrics:
    - metrics.lndo.site:8100
services:
  metrics:
    type: node:14
    command: yarn run dev:metrics
    port: 8100
    ssl: true
    sslExpose: false
tooling:
  node:
    service: metrics
  yarn:
    service: metrics
