[build]
  functions = "functions"
  # This sort of lets us build on tagged commits
  ignore = "if git diff $CACHED_COMMIT_REF $COMMIT_REF ./package.json | grep - | grep version && git diff $CACHED_COMMIT_REF $COMMIT_REF ./package.json | grep + | grep version; then exit 1; else exit 0; fi"

# Domain redirects
[[redirects]]
  from = "https://stats-v2.kalabox.io/*"
  to = "https://metrics.lando.dev/:splat"
  status = 301
[[redirects]]
  from = "https://stats.lando.dev/*"
  to = "https://metrics.lando.dev/:splat"
  status = 301
[[redirects]]
  from = "https://metrics.lndo.io/*"
  to = "https://metrics.lando.dev/:splat"
  status = 301
[[redirects]]
  from = "https://stats.lndo.io/*"
  to = "https://metrics.lando.dev/:splat"
  status = 301
[[redirects]]
  from = "https://metrics.devwithlando.io/*"
  to = "https://metrics.lando.dev/:splat"
  status = 301
[[redirects]]
  from = "https://stats.devwithlando.io/*"
  to = "https://metrics.lando.dev/:splat"
  status = 301

# API redirects
[[redirects]]
  from = "/"
  to = "/.netlify/functions/ping"
  status = 200
[[redirects]]
  from = "/ping"
  to = "/.netlify/functions/ping"
  status = 200
[[redirects]]
  from = "/status/*"
  to = "/.netlify/functions/status/:splat"
  status = 200
[[redirects]]
  from = "/metrics/v2/*"
  to = "/.netlify/functions/metrics/:splat"
  status = 200
