[build]
  # This sort of lets us build only on tagged commits to prod
  # [context.production]
  #   ignore = "if git diff $CACHED_COMMIT_REF $COMMIT_REF ./package.json | grep - | grep version && git diff $CACHED_COMMIT_REF $COMMIT_REF ./package.json | grep + | grep version; then exit 1; else exit 0; fi"

[functions]
  directory = "functions"
  node_bundler = "esbuild"

# Domain rewrites
[[redirects]]
  from = "https://stats-v2.kalabox.io/*"
  to = "https://telemetry.lando.dev/:splat"
  status = 200
[[redirects]]
  from = "https://stats.lando.dev/*"
  to = "https://telemetry.lando.dev/:splat"
  status = 200
[[redirects]]
  from = "https://metrics.lndo.io/*"
  to = "https://telemetry.lando.dev/:splat"
  status = 200
[[redirects]]
  from = "https://stats.lndo.io/*"
  to = "https://telemetry.lando.dev/:splat"
  status = 200
[[redirects]]
  from = "https://metrics.devwithlando.io/*"
  to = "https://telemetry.lando.dev/:splat"
  status = 200
[[redirects]]
  from = "https://stats.devwithlando.io/*"
  to = "https://telemetry.lando.dev/:splat"
  status = 200
[[redirects]]
  from = "https://metrics.lando.dev/*"
  to = "https://telemetry.lando.dev/:splat"
  status = 200

# API rewrites
[[redirects]]
  from = "/"
  to = "/.netlify/functions/ping"
  status = 200
[[redirects]]
  from = "/ping"
  to = "/.netlify/functions/ping"
  status = 200
[[redirects]]
  from = "/metrics/*"
  to = "/.netlify/functions/metrics/:splat"
  status = 200
[[redirects]]
  from = "/status/*"
  to = "/.netlify/functions/status/:splat"
  status = 200
